// <auto-generated />
using AnuncioWeb.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnuncioWeb.Migrations
{
    [DbContext(typeof(AnuncioContext))]
    [Migration("20210219140155_StartBanco")]
    partial class StartBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("AnuncioWeb.Models.Anuncio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ano");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("observacao")
                        .IsRequired();

                    b.Property<int>("quilometragem");

                    b.Property<string>("versao")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.HasKey("id");

                    b.ToTable("Anuncios");
                });
#pragma warning restore 612, 618
        }
    }
}
